#   A basic travis.yml boilerplate for Django projects
#
#   The set-up assumes a postgreSQL database.
#
#   Replace the following variables in the code:
# * your_project_settings
# * your_github_username
# * your_repo

language: python

python:
  - 3.6

services: sqlite3

env:
  - XhyBcB0EmL4o1tk5H1qfZLUWqCLpD4OAloUaO

install:
  - pip install -r requirements.txt
  - pip install coveralls

script:
  - python manage.py makemigrations
  - python manage.py migrate
  - coverage run --source=. manage.py test

after_success:
  - coveralls
