# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-27 04:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nec', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoneyUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=1024)),
                ('title', models.CharField(max_length=1024)),
                ('text', models.TextField(null=True)),
                ('balance', models.IntegerField()),
                ('created_date', models.DateTimeField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='bucketlist',
            name='deadline_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bucketlist',
            name='text',
            field=models.TextField(null=True),
        ),
    ]
