# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-01 18:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nec_bank', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='money',
            name='created_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
